#' Save pheatmap function (png or pdf)
#'
#' Function to save the heat map generated by pheatmap, as first written by Matt
#' Whitaker (https://gist.github.com/mathzero)
#'
#' function detects '.png' or '.pdf' in the declared filename and assigns that
#' file type
#'
#' @param x pheatmap object
#' @param filename Desired filename, containing png or pdf
#' @param width Plot width for file
#' @param height Plot height for file
#'
#' @export

save_pheatmap <- function(x, filename, width = 12, height = 12) {
  stopifnot(!missing(x))
  stopifnot(!missing(filename))
  if(grepl(".pdf", filename)) {
    print(paste0("Saving as ", filename))
    pdf(filename, width = width, height = height)
    grid::grid.newpage()
    grid::grid.draw(x$gtable)
    dev.off()
  } else {
    if(grepl(".png", filename)) {
      print(paste0("Saving as ", filename))
    } else {
      filename = paste0(filename, ".png")
      print(paste0("Saving as ", filename))
    }
    png(filename, width = width, height = height, units = "in", res = 300)
    grid::grid.newpage()
    grid::grid.draw(x$gtable)
    dev.off()
  }
}
