name: Deploy pkgdown Site

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install dependencies
        run: Rscript -e 'install.packages("pkgdown")'
      
      - name: Build pkgdown Site
        run: Rscript -e 'pkgdown::build_site()'
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: master  # Use 'master' for user or organization sites.
          destination_dir: guzioR  # Target directory within the branch
